apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: db
spec:
  instances: 1

  imageName: localhost:10010/postgresql-vectors:16.2-10

  superuserSecret:
    name: cloudnative-pg-superuser
  enableSuperuserAccess: true

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cloudnative-pg-app-user
      postInitSQL:
        - "CREATE EXTENSION cube;"
        - "CREATE EXTENSION earthdistance;"
        - "CREATE EXTENSION vectors;"

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  storage:
    size: 50Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
