image:
  repository: netboxcommunity/netbox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v4.0.7

readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 15

postgresql:
  enabled: false

externalDatabase:
  host: cnpg-cluster-rw.db
  port: 5432
  database: netbox
  username: netbox
  existingSecret: netbox-secret

  # The following settings also apply when using the bundled PostgreSQL chart:
  sslMode: prefer
  connMaxAge: 300
  disableServerSideCursors: false
  targetSessionAttrs: read-write

internalIPs:
  - 10.233.64.1
  - 172.16.1.11

metricsEnabled: true
serviceMonitor:
  enabled: true

timezone: America/New_York
existingSecret: netbox-secret

redis:
  enabled: false

tasksRedis:
  database: 0
  ssl: false
  insecureSkipTlsVerify: false
  caCertPath: ""
  host: &redis-host redis-master.db.svc
  port: &redis-port 6379

cachingRedis:
  database: 1
  ssl: false
  insecureSkipTlsVerify: false
  caCertPath: ""
  host: *redis-host
  port: *redis-port

persistence:
  enabled: true
  existingClaim: netbox-media

ingress:
  enabled: true
  className: nginx
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: netbox.png
    gethomepage.dev/description: "Infrastructure inventory and IPAM solution"
  hosts:
    - host: &host netbox.hermleigh.cc
      paths:
        - /
  tls:
    - secretName: external-wildcard-certificate
      hosts:
        - *host

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi

extraContainers:
  - name: graphite
    image: netreplica/graphite
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nrx-files
        mountPath: /htdocs/default
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
    securityContext:
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true
      runAsNonRoot: false
      runAsUser: 0
      runAsGroup: 0
      capabilities:
        drop:
          - all
        add:
          - NET_BIND_SERVICE
          - SETUID
          - SETGID

extraVolumes:
  - name: nrx-files
    emptyDir: {}

extraVolumeMounts:
  - name: nrx-files
    mountPath: /graphite

# Configuration of Cron settings
housekeeping:
  enabled: true
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  restartPolicy: OnFailure
  schedule: '0 7 * * 0'
  successfulJobsHistoryLimit: 2
  suspend: false
