# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      linkwarden:
        image:
          repository: ghcr.io/linkwarden/linkwarden
          tag: v2.4.8

        env:
          NEXTAUTH_URL: http://localhost:3000
        envFrom:
          - secretRef:
              name: linkwarden-secret
          - secretRef:
              name: linkwarden-db-url

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/icon: linkwarden.png
      gethomepage.dev/name: Linkwarden
    hosts:
      - host: &host linkwarden.hermleigh.cc
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

persistence:
  data:
    existingClaim: linkwarden
    globalMounts:
      - path: /data/data
