---
dependencies:
  - role: network/cilium
    when: kube_network_plugin == 'cilium' or cilium_deploy_additionally | default(false) | bool
    tags:
      - cilium

  - role: network/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel
