---
- Infrastructure:
    - OPNsense:
        href: &opnsense https://growler.hermleigh.home
        icon: opnsense.png
        description: OpnSense Router/Gateway/Firewall
        widget:
          type: opnsense
          url: *opnsense
          username: "{{HOMEPAGE_VAR_OPNSENSE_API_KEY}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_API_SECRET}}"
    - AdGuard:
        href: &adguard http://adguard.hermleigh.home
        icon: adguard-home.png
        description: DNS Adblocking
        widget:
          type: adguard
          url: *adguard
          username: "{{HOMEPAGE_VAR_ADMIN_USER}}"
          password: "{{HOMEPAGE_VAR_ADMIN_PWD}}"
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust.png
        description: Cloudflared Tunnel
        # widget:
        #   type: cloudflared
        #   accountid: {{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNT}}
        #   tunnelid: {{HOMEPAGE_VAR_CLOUDFLARED_TUNNEL}}
        #   key: {{HOMEPAGE_VAR_CLOUDFLARED_TOKEN}}
    - ntop-ng:
        href: "https://growler.hermleigh.home:3443/"
        icon: ntopng.png
        description: "Network Top - Next Generation"
    - Maltrail:
        href: "http://maltrail.hermleigh.home/"
        icon: https://raw.githubusercontent.com/stamparm/maltrail/master/html/images/mlogo.png
        description: Malicious traffic detection system

- Monitoring:
    - Crowdsec:
        href: https://app.crowdsec.net/
        icon: crowdsec.png
        description: Crowd-based cyber security threat detection & mitigation
