---
title: Dashboard
theme: dark
color: neutral
useEqualHeights: true
layout: # key by group name in services.yaml
  Apps & Services:
    style: row
    columns: 4
    tab: Apps
    icon: mdi-application
  Media:
    style: row
    columns: 4
    tab: Apps
    icon: mdi-movie-open
  Downloads:
    style: row
    columns: 4
    tab: Apps
    icon: mdi-download
  Infrastructure:
    style: row
    columns: 4
    tab: Infrastructure
  Monitoring:
    style: row
    columns: 4
    tab: Infrastructure
