---
fail_fast: false

exclude: |
  (?x)^(
      docs/_assets/.*
    | .*\.sops\.(toml|yaml)
    | .*\.drawio
  )$

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - -c
          - .github/linters/.yamllint
          - --no-warnings

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        args: [--whitespaces-count, '2']  # defaults to: 4

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            docs/.*
          )$
      # - id: shellcheck
      # - id: shfmt

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.5.0
    hooks:
      - id: ansible-lint
        args:
          - -c
          - .github/linters/.ansible-lint
        additional_dependencies:
          - netaddr
        always_run: false
        files: ^(infrastructure|playbooks)/
        exclude: ^infrastructure/terraform
        exclude_types: [markdown, shell]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .github/linters/.markdownlint.yaml
        exclude: "^.git"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
