---
collections:
  - name: lvrfrc87.git_acp
    type: galaxy
  - name: freeipa.ansible_freeipa
    type: galaxy
  - ansible.posix
  - ansible.windows
  - community.crypto
  - community.general
  - community.libvirt
  - community.sops
  - community.postgresql
  - community.mysql
  - community.grafana
  - kubernetes.core
  - cisco.ios
  - name: ansibleguy.opnsense
    type: galaxy
    version: 1.2.9
