# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      linkding:
        image:
          repository: sissbruecker/linkding
          tag: 1.19.1
        env:
          LD_DB_ENGINE: "postgres"
          LD_DB_HOST: cnpg-cluster-rw.db
          LD_DB_PORT: 5432
          LD_DB_DATABASE: linkding
        envFrom:
          - secretRef:
              name: linkding-secret
        resources:
          requests:
            cpu: 12m
            memory: 64M
          limits:
            memory: 256M

defaultPodOptions:
  enableServiceLinks: false

service:
  main:
    controller: main
    ports:
      http:
        port: 9090

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "A bookmark manager with read-it-later and archiving functionality"
      gethomepage.dev/icon: linkding.png
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/name: Linkding
    hosts:
      - host: &host linkding.hermleigh.cc
        paths:
          - path: /
            service:
              port: http
              identifier: main
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate
