# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      homebox:
        image:
          repository: ghcr.io/hay-kot/homebox
          tag: v0.10.3@sha256:b1fbca6fc1ad2bd3634d13056d1bc0242cf92e9bad4ca21ce57589be3fe4987e
        env:
          TZ: America/New_York
          HBOX_LOG_LEVEL: info
          HBOX_LOG_FORMAT: text
          HBOX_MEB_MAX_UPLOAD_SIZE: 10
        resources:
          requests:
            cpu: 10m
            memory: 256M
          limits:
            memory: 256M
service:
  main:
    controller: main
    ports:
      http:
        port: 7745
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Homebox
      gethomepage.dev/description: "Inventory management system"
      gethomepage.dev/icon: homebox.svg
      gethomepage.dev/group: "Apps & Services"
    hosts:
      - host: &host homebox.hermleigh.cc
        paths:
          - path: "/"
            pathType: "Prefix"
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate

persistence:
  data:
    enabled: true
    existingClaim: homebox
