#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseer-config
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jellyseer-config
    namespace: media
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 153.0Gi
  local:
    path: /srv/cluster/volumes/media/jellyfin/jellyseer-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  namespace: media
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 153.0Gi
  storageClassName: local-storage
  volumeName: jellyseer-config
