# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      home-assistant:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2024.8.0
        env:
          TZ: America/New_York
          HASS_HTTP_TRUSTED_PROXY_1: 10.0.0.0/8
        probes: &probes
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 1254M
          limits:
            memory: 1254M
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
      code:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.91.1
        env:
          TZ: America/New_York
        args: [
          "--auth", "none",
          "--user-data-dir", "/config/.vscode",
          "--extensions-dir", "/config/.vscode",
          "--port", "8080",
          "/config"
        ]
        probes: *probes
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 512Mi

defaultPodOptions:
  securityContext:
    fsGroup: 997
    fsGroupChangePolicy: OnRootMismatch

service:
  main:
    controller: main
    ports:
      http:
        port: 8123
        primary: true
      code:
        port: 8080

ingress:
  home-assistant:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "Home Assistant"
      gethomepage.dev/icon: home-assistant.svg
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/name: Home Assistant
    hosts:
      - host: &host home-assistant.hermleigh.cc
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate
  code:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "VSCode Editor for Home Assistant"
      gethomepage.dev/icon: coder.svg
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/name: Home Assistant Coder
    hosts:
      - host: &code-host hass-code.hermleigh.cc
        paths:
          - path: /
            service:
              identifier: main
              port: code
    tls:
      - hosts:
          - *code-host
        secretName: external-wildcard-certificate

persistence:
  config:
    enabled: true
    existingClaim: home-assistant
  tmp:
    type: emptyDir
  run:
    type: emptyDir
