# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/main/bitnami/redis/values.schema.json
clusterDomain: seawolf

architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: false
  service:
    type: LoadBalancer
  dnsConfig:
    options:
      - name: ndots
        value: "8"

metrics:
  enabled: true
  prometheusRule:
    enabled: true
    namespace: monitoring
  serviceMonitor:
    enabled: true
    interval: 1m

useExternalDNS:
  enabled: true
