#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-api-data
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mealie-api-data
    namespace: home
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 153.0Gi
  local:
    path: /srv/cluster/volumes/home/mealie/mealie-api-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-api-data
  namespace: home
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 153.0Gi
  storageClassName: local-storage
  volumeName: mealie-api-data
