#
# Ansible managed
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
generators:
- ./secret-generator.yaml
configMapGenerator:
- name: homepage-config
  files:
  - ./config/bookmarks.yaml
  - ./config/docker.yaml
  - ./config/kubernetes.yaml
  - ./config/services.yaml
  - ./config/settings.yaml
  - ./config/widgets.yaml
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: homepage
      app.kubernetes.io/instance: homepage
