---
- name: Ensure namespace exists | {{ app.namespace }}
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ app.namespace }}"

- name: Set secret fact | {{ app.name }}
  set_fact:
    secrets: {}

- name: Manage app secrets | {{ app.name }}
  when: app.secrets is defined
  block:
    - name: Manage app secrets | {{ app.name }}
      include_tasks: manage_secret.yml
      loop: "{{ app.secrets | dict2items(key_name='name') }}"
      loop_control:
        loop_var: secret
      vars:
        sops_file: "{{ (app.app_dir, secret.name+'.sops.yaml')| path_join }}"

    - name: Render KSOPS generator template | {{ app.name }}
      template:
        src: secret-generator.yaml.j2
        dest: "{{ app.app_dir }}/secret-generator.yaml"
        force: true
      register: ksops

- name: Get Kubernetes Cluster info
  kubernetes.core.k8s_cluster_info:
  register: cluster_info

- name: "Install Kustomization file | {{ app.name }}"
  template:
    src: kustomization.yaml.j2
    dest: "{{ app.app_dir }}/kustomization.yaml"
    mode: "0644"
    force: true
  register: kustomization
  when: ('kustomize' in app) or ('secrets' in app)
  vars:
    k8s_apis: "{{ cluster_info.apis.keys() | list }}"

- name: Storage
  when: ('localStorage' in app)
  vars:
    storage_dirs: []
    paths: []
  block:
    - name: Find Storage Dirs | {{ app.name }}
      set_fact:
        paths: "{{ paths +
            [ (item.path|default('') is abs)
                | ternary(
                    item.path|default(''),
                    (
                      local_storage_root_dir,
                      app.namespace,
                      app.name,
                      item.path | default(item.name) | default(app.name)
                    )
                ) | path_join ]
          }}"
      with_items:
      - "{{ app.localStorage }}"
      loop_control:
        label: "{{ item.path | default(app.name) }}"

    - name: Ensure target directories exist | {{ app.name }}
      delegate_to: parche
      become: true
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
        mode: "0775"
        group: kube
      loop: "{{ paths }}"

    - name: Get filesystem size for each directory | {{ app.name }}
      delegate_to: parche
      command: "df -h {{ item }}"
      register: fs_sizes
      loop: "{{ paths }}"

    - name: Build storage_dirs | {{ app.name }}
      set_fact:
        storage_dirs: "{{ storage_dirs +
            [{
              'path': item,
              'modes': app.localStorage[i].modes | default(['ReadWriteOnce']),
              'name': app.localStorage[i].name | default(app.name),
              'size': ((fs_sizes.results[i].stdout | community.general.jc('df'))[0]['size'] / (10 ** 9)) ~ 'Gi'
            }]
          }}" # noqa jinja[invalid]
      loop: "{{ paths }}"
      loop_control:
        index_var: i

    - name: Generate storage manifest file | {{ app.name }}
      template:
        src: storage.yaml.j2
        dest: "{{ app.app_dir }}/storage.yaml"
        mode: "0644"
        force: true
  always:
    - name: Clear variables
      set_fact:
        storage_dirs: []
        paths: []

- name: Ensure cluster/bootstrap namespace dir exists | {{ app.name }}
  file:
    path: "{{ app.manifest_file | dirname }}"
    state: directory

- name: ArgoCD application manifest | {{ app.name }}
  template:
    src: application.yaml.j2
    dest: "{{ app.manifest_file }}"
    mode: "0644"
    force: true
  register: application
  tags: manifest

- name: "Application specific pre-start tasks | {{ app.name }}"
  include_tasks: "{{ taskfile }}"
  with_first_found:
    - files:
        - "pre-start/{{ app.name }}.yml"
      skip: true
  loop_control:
    loop_var: taskfile
  register: app_tasks
  tags:
    - app_tasks

- name: Commit changes to app files | {{ app.name }}
  lvrfrc87.git_acp.git_acp:
    path: "{{ root_dir }}"
    comment: "[{{ app.name }}] Updated application config files\n\n{{ files | to_nice_yaml }}"
    add: "{{  files  }}"
    url: "{{ git_repo_ssh_url }}"
    push: "{{ git_push | default(true) }}"
    branch: "{{ git_branch }}"
    push_force: "{{ git_push_force | default(false) }}"
  when:
    - files | length > 0
    - not batch_apps | default(false)
  register: git_commit
  tags: commit
  vars:
    files: |-
      {{ [
          lookup('pipe','git status --porcelain -- ' ~ app.app_dir).splitlines()
            | reject('match','D')
            | map('split',' ')
            | map('last'),

          lookup('pipe','git status --porcelain -- ' ~ app.manifest_file).split(' ')| last,

          lookup('pipe','git status --porcelain').splitlines()
            | reject('match','[ D?]')
            | map('split', ' ')
            | map('last')
      ]  | reject('eq', '') | flatten }}

- name: Wait a minute for the commit to land in Github
  pause:
    seconds: 15
  tags: commit
  when:
    - git_commit is not skipped
    - git_push | default(true) is true

- name: Launch application when wave is defined
  when: app_tasks
  block:
    - name: Launch application now | {{ app.name }}
      kubernetes.core.k8s:
        src: "{{ app.manifest_file }}"
        server_side_apply:
          field_manager: ansible
      tags: app_tasks

    - name: "Application specific post-launch tasks | {{ app.name }}"
      include_tasks: "{{ taskfile }}"
      with_first_found:
        - files:
            - "post-launch/{{ app.name }}.yml"
          skip: true
      loop_control:
        loop_var: taskfile
      register: post_launch_tasks
      tags:
        - app_tasks

- name: Pause before continuing to next app | {{ ansible_loop.nextitem.name }}
  pause:
    prompt: "Continue to {{ ansible_loop.nextitem.name }}"
  when:
    - not ansible_loop.last
    - not app_no_loop_pause|default(false)
