apiVersion: v1
data:
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:IltecOPBdIcrxORZzahCEufoc1Q66GQVhK4a1UudiHQfonLZdRuNfQ==,iv:Qc70qyxfJRkVpnZLRyPhN24VTFpb9MZF/MO/DFl7uPA=,tag:9FjPiopIXadvvv62abMjdA==,type:str]
kind: Secret
metadata:
    name: photoprism-secret
    namespace: media
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e764qpphm5nlzp04qf6zcq8f400390d9wmzramq84hqp60k6qyvqsvgg45
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaGtyekZhMGJrb1JhelpB
            STlHWEliN2pXcmtLeTRiTkl2RHNMYzkrd21jCklLWWdQSlZDaHJlUFZQUUpkbVYr
            RFp3UUFMM0lFT1p1NzNZbmQwRWo5OG8KLS0tIEV4NExQWnV6bUttSW1oZW5GRGZH
            ZGcvUXhSM01BbDhuMHhCdVNNMlFGL0EKT7SlopXhzaQwttXsxFhosVj7ih+EeU77
            DLaHabBWjDkynFfjU4mVU/H37++MIxYdGgEPU6GOoNNsZhA8PG5oiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-26T21:50:43Z"
    mac: ENC[AES256_GCM,data:cCaxeweQhd8A9AkjlzmjMxVWEAA7wa5NLFpib3mBCtIdbvJESDCadcVUsgt0nmLMkftidLkl5H0ZDTKJYk46VM35VF7sMs0k00wAOzldKMAbwGSpFwhF7eBTJ1unkocK6nemRaM1U7UbXsVw9SozPHgfEZIdXbLI4hMs5UGzGnw=,iv:89xptkgHQvLLwJBLxzfek11H79LBtgL2K0VZQpTzF9A=,tag:EYZHEYpzZOQf5dVkzO7abg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
