#
# Ansible managed
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
generators:
- ./secret-generator.yaml
configMapGenerator:
- name: bazarr-scripts
  files:
  - ./scripts/post-process.sh
generatorOptions:
  disableNameSuffixHash: true
resources:
- ./storage.yaml
