apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik-system
  annotations:
    cert-manager.io/common-name: traefik.seawolf.hermleigh.home
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: '384'
    cert-manager.io/subject-countries: US
    cert-manager.io/subject-organizationalunits: Kubernetes - Services
    cert-manager.io/subject-organizations: HERMLEIGH.HOME
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.seawolf.hermleigh.home`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
