---
providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesIngress:
    publishedService:
      # To fix argocd stuck in progressing https://github.com/argoproj/argo-cd/issues/968#issuecomment-955976397
      enabled: true
      # Need to override path since otherwise the namespace is set as default
      pathOverride: traefik-system/traefik

additionalArguments:
  - "--api"
  - "--api.insecure=true"

logs:
  general:
    level: ERROR

ingressRoute:
  dashboard:
    enabled: false

persistence:
  enabled: false

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: ingress-pool
    external-dns.alpha.kubernetes.io/hostname: traefik.seawolf.hermleigh.home
  externalTrafficPolicy: Local
