apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: https://avatars.githubusercontent.com/u/4921466?s=48&v=4
    gethomepage.dev/name: Keycloak
    gethomepage.dev/description: "Single-Sign On Provider"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/href: "https://keycloak.hermleigh.cc"
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  name: keycloak-ingress
  namespace: infrastructure
spec:
  ingressClassName: nginx
  rules:
  - host: &host keycloak.hermleigh.cc
    http:
      paths:
      - backend:
          service:
            name: keycloak-service
            port:
              number: &port 8443
        pathType: ImplementationSpecific
  defaultBackend:
    service:
      name: keycloak-service
      port:
        number: *port
  tls:
    - hosts:
        - *host
      secretName: external-wildcard-certificate
