---
- name: Add HashiCorp apt repository key
  block:
    - name: Download Hashicorp repo GPG key
      get_url:
        url: "{{ hashicorp_repo_key_url }}"
        dest: /etc/apt/trusted.gpg.d/hashicorp.asc
        mode: '0644'
        force: true

    - name: HashiCorp  | apt source
      apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: true

- name: Load Root CA into system ca trust store
  copy:
    dest: "/usr/local/share/ca-certificates/{{ domain_name }}-root.crt"
    content: "{{ root_ca.crt | b64decode }}"
  notify:
    - "update ca truststore"

- name: Ensure a locale exists
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
