apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: services
  labels:
    app.kubernetes.io/name: grocy
  annotations:
    configmap.reloader.stakater.com/reload: "grocy-config,grocy-cm"
    kompose.cmd: kompose convert -n services -f docker-compose.yml --service-group-mode label
    kompose.controller.type: Deployment
    kompose.service.expose: grocy.hermleigh.home, grocy
    kompose.service.expose.tls-secret: grocy-tls-ingress
    kompose.service.group: grocy
    kompose.service.type: ClusterIP
    kompose.version: 1.30.0 (9d8dcb518)
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
      annotations:
        kompose.cmd: kompose convert -n services -f docker-compose.yml --service-group-mode label
        kompose.service.expose: "false"
        kompose.service.group: grocy
        kompose.version: 1.30.0 (9d8dcb518)
    spec:
      initContainers:
        - name: link-config
          image: busybox:1.28
          command: ['sh', '-c', 'ln -sfv /config/config.php /var/www/data']
          volumeMounts:
            - name: grocy
              mountPath: /var/www/data
            - mountPath: /config
              name: grocy-config
      containers:
        - name: grocy-frontend
          image: docker.io/grocy/frontend:v4.2.0
          envFrom:
            - configMapRef:
                name: grocy-cm
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 80m
              memory: 256Mi
            limits:
              cpu: 220m
              memory: 512Mi
          volumeMounts:
            - mountPath: /tmp
              name: grocy-tmpfs0
        - name: grocy-backend
          image: docker.io/grocy/backend:v4.2.0
          envFrom:
            - configMapRef:
                name: grocy-cm
          ports:
            - name: web
              containerPort: 9000
              protocol: TCP
          resources:
            requests:
              cpu: 80m
              memory: 256Mi
            limits:
              cpu: 220m
              memory: 512Mi
          volumeMounts:
            - name: grocy
              mountPath: /var/www/data
            - mountPath: /var/www/data/viewcache
              name: grocy-tmpfs1
            - mountPath: /config
              name: grocy-config
            - mountPath: /tmp
              name: grocy-tmpfs0
      volumes:
        - name: grocy
          persistentVolumeClaim:
            claimName: grocy
        - name: grocy-config
          configMap:
            name: grocy-config
        - name: grocy-tmpfs0
          emptyDir: &tempfs
            medium: Memory
            sizeLimit: 128Mi
        - name: grocy-tmpfs1
          emptyDir: *tempfs
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - backend
      securityContext:
        fsGroup: 997
        runAsGroup: 997
        runAsUser: 997
