#
# Ansible managed
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
configMapGenerator:
- name: grocy-config
  files:
  - ./config.php
  options:
    disableNameSuffixHash: true
    labels:
      app.kubernetes.io/name: grocy
      app.kubernetes.io/instance: grocy
resources:
- ./cm.yaml
- ./deployment.yaml
- ./ingress.yaml
- ./storage.yaml
- ./svc.yaml
