apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-wildcard
  namespace: infrastructure
spec:
  secretName: external-wildcard-certificate
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: hermleigh.cc
  subject:
    organizations:
      - "HERMLEIGH.CC"
    organizationalUnits:
      - "Hermleigh House Network"
    countries:
      - "US"
  dnsNames:
    - "*.hermleigh.cc"
    - "hermleigh.cc"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
