apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphite
  namespace: infrastructure
  labels:
    name: graphite
spec:
  rules:
  - host: &host graphite.hermleigh.cc
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: graphite
            port:
              number: 80
  tls:
    - hosts:
        - *host
      secretName: external-wildcard-certificate
