---
- name: Cilium | Start Resources
  kubernetes.core.k8s:
    src: "{{ kube_config_dir }}/{{ item.item.name }}-{{ item.item.file }}"
    namespace: kube-system
    state: present
    kubeconfig: "{{ kubeconfig_file }}"
    verify_ssl: false
  loop: "{{ cilium_node_manifests.results }}"
  when: inventory_hostname == groups['kube_control_plane'][0] and not item is skipped

- name: Cilium | Wait for pods to run
  command: "{{ kubectl }} --kubeconfig {{ kubeconfig_file }} -n kube-system get pods -l k8s-app=cilium -o jsonpath='{.items[?(@.status.containerStatuses[0].ready==false)].metadata.name}'"  # noqa literal-compare
  register: pods_not_ready
  until: pods_not_ready.stdout.find("cilium")==-1
  retries: "{{ cilium_rolling_restart_wait_retries_count | int }}"
  delay: "{{ cilium_rolling_restart_wait_retries_delay_seconds | int }}"
  failed_when: false
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: Cilium | Hubble install
  kubernetes.core.k8s:
    src: "{{ kube_config_dir }}/addons/hubble/{{ item.item.name }}-{{ item.item.file }}"
    namespace: kube-system
    kubeconfig: "{{ kubeconfig_file }}"
    state: present
    verify_ssl: false
  loop: "{{ cilium_hubble_manifests.results }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0] and not item is skipped
    - cilium_enable_hubble and cilium_hubble_install
