---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: 'False'
  name: local-path-videos
provisioner: rancher.io/local-path
parameters:
  nodePath: /videos/volumes
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: 'False'
  name: local-path-shared
provisioner: rancher.io/local-path
parameters:
  nodePath: /share/volumes
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
