---
argument_specs:
  main:
    options:
      app_deploy_list:
        type: list
        description: A list of applications to deploy instead of the entire list
        required: false
        default: []
      app_skip_list:
        type: list
        description: A list of applications to not deploy out of the entire list
        required: false
        default: []
      app_start_wave:
        type: int
        required: false
        description: Wave number to start deployment from
      app_start_at:
        type: str
        description: Name of the app to start deploying from
        required: false
      app_no_loop_pause:
        type: bool
        required: false
        default: false
        description: Don't wait for user input before proceeding to next app in deployment
      batch_apps:
        type: bool
        required: false
        default: false
        description: Wait until deployment is complete to create a git commit instead of once per app.
