#
# Ansible managed
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  finalizers:
  - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: grafana
    namespace: monitoring
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: local-storage
  capacity:
    storage: 153.0Gi
  local:
    path: /srv/cluster/volumes/monitoring/kube-prometheus-stack/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - parche
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 153.0Gi
  storageClassName: local-storage
  volumeName: grafana
