#
# Ansible managed
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
generators:
- ./secret-generator.yaml
configMapGenerator:
- name: wger-env
  envs:
  - config.env
  options:
    disableNameSuffixHash: true
resources:
- ./storage.yaml
