# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    annotations:
      configmap.reloader.stakater.com/reload: wger-env
    containers:
      wger:
        image: &image
          repository: wger/server
          tag: latest
        envFrom:
          - configMapRef:
              name: wger-env
          - secretRef:
              name: wger-secret
        resources: &resources
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 512Mi
      wger-celery-worker:
        image: *image
        command: /start-worker
        envFrom:
          - configMapRef:
              name: wger-env
          - secretRef:
              name: wger-secret
        resources: *resources
      wger-celery-beat:
        image: *image
        command: /start-beat
        envFrom:
          - configMapRef:
              name: wger-env
          - secretRef:
              name: wger-secret
        resources: *resources

service:
  main:
    controller: main
    ports:
      http:
        port: 8000

ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: Wger
      gethomepage.dev/description: "Personal workout/food tracker"
      gethomepage.dev/icon: "wger.svg"
      gethomepage.dev/group: "Apps & Services"
    hosts:
      - host: &host wger.hermleigh.cc
        paths:
          - path: "/"
            pathType: "Prefix"
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate

persistence:
  media:
    enabled: true
    existingClaim: wger
    globalMounts:
      - path: /home/wger/src/media
