---
# Whether to deploy the container engine
deploy_container_engine: "{{ inventory_hostname in groups['k8s_cluster'] or etcd_deployment_type == 'docker' }}"

## Container runtime
## docker for docker, crio for cri-o and containerd for containerd.
container_manager: crio

# Enable crun as additional container runtime
# When enabled, it requires container_manager=crio
crun_enabled: false

runc_enabled: true

# Project versions
crio_version: v1.29.2
crictl_version: v1.29.0
runc_version: v1.1.12
skopeo_version: v1.14.2

# CRI socket path
cri_socket_path: /var/run/crio/crio.sock
cri_socket: "unix://{{ cri_socket_path }}"

image_info_command: "{{ bin_dir }}/crictl images --verbose | awk -F ': ' '/RepoTags|RepoDigests/ {print $2}' | tr '\n' ','"
image_pull_command: "{{ bin_dir }}/crictl pull"

# Arch of Docker images and needed packages
image_arch: "{{host_architecture | default('amd64')}}"


# kubernetes image repo define
kube_image_repo: registry.k8s.io

# docker image repo define
docker_image_repo: docker.io

# quay image repo define
quay_image_repo: quay.io

# github image repo define (ex multus only use that)
github_image_repo: ghcr.io

crio_insecure_registries:
  - "{{ kube_image_repo }}"
  - "{{ quay_image_repo }}"
  - "{{ docker_image_repo }}"
# crio_registry_auth:
#   - registry: 10.0.0.2:5000
#     username: user
#     password: pass

crio_registries:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: registry-1.docker.io ## REQUIRED
    unqualified: true
    mirrors:
      # - location: 172.20.100.52:5000
      #   insecure: true
      - location: mirror.gcr.io
        insecure: false
  # - prefix: quay.io
  #   unqualified: true
  # - prefix: registry.k8s.io
  #   unqualified: true
