---
# DNS configuration.
# dns_timeout: 2
# dns_attempts: 2
# Custom search domains to be added in addition to the default cluster search domains
# searchdomains:
#   - svc.{{ cluster_name }}
#   - default.svc.{{ cluster_name  }}
# Remove default cluster search domains (``default.svc.{{ dns_domain }}, svc.{{ dns_domain }}``).
# remove_default_searchdomains: false
# Can be coredns, coredns_dual, manual or none
dns_mode: coredns

# CoreDNS
coredns_version: 'v1.10.1'

# Enable k8s_external plugin for CoreDNS
enable_coredns_k8s_external: true
k8s_external_zone: "{{cluster_name}}.{{ domain_name }}"
coredns_k8s_external_zone: "{{ k8s_external_zone }}"
# Enable endpoint_pod_names option for kubernetes plugin
enable_coredns_k8s_endpoint_pod_names: false
# Set forward options for upstream DNS servers in coredns (and nodelocaldns) config
# dns_upstream_forward_extra_opts:
#   policy: sequential
# Apply extra options to coredns kubernetes plugin
coredns_kubernetes_extra_opts:
  - 'ttl 30'
# Forward extra domains to the coredns kubernetes plugin
# coredns_kubernetes_extra_domains: ''

# Ip address of the kubernetes dns service
dns_server: "{{ kube_service_addresses|ipaddr('net')|ipaddr(10)|ipaddr('address') }}"
dns_domain: "{{ cluster_name }}"

# Coredns version should be supported by corefile-migration (or at least work with)
# bundle with kubeadm; if not 'basic' upgrade can sometimes fail

coredns_image_repo: "{{ kube_image_repo }}/coredns/coredns"
coredns_image_tag: "{{ coredns_version }}"
