#
# Ansible managed
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
generators:
- ./secret-generator.yaml
configMapGenerator:
- name: nginx-config
  files:
  - nginx.conf
  options:
    disableNameSuffixHash: true
