# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      linkace:
        image:
          repository: linkace/linkace
          tag: v1.12.2-php-nginx

        env:
          APP_KEY: sC4Zj5PHEg4O1oP+dBVGC5hdninaEgDQ
          DB_HOST: mysql.db
          DB_DATABASE: linkacedb
          DB_CONNECTION: mysql
          REDIS_HOST: redis-master.db
          # REDIS_PASSWORD: password
          # REDIS_PORT: 6379
          # SESSION_DRIVER: redis
          # CACHE_DRIVER: redis

        envFrom:
          - secretRef:
              name: linkace-secret

ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/name: Linkace
      gethomepage.dev/icon: linkace.png
    hosts:
      - host: &host linkace.hermleigh.cc
        paths:
          - path: /
            service:
              port: http
              identifier: main
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate

service:
  main:
    controller: main
    ports:
      http:
        port: 80
