# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    containers:
      stirling-pdf:
        image:
          repository: docker.io/frooodle/s-pdf
          tag: 0.27.0
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            memory: 256Mi
service:
  main:
    controller: main
    ports:
      http:
        port: 8080
ingress:
  main:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: "Apps & Services"
      gethomepage.dev/name: Stirling PDF
      gethomepage.dev/icon: stirling-pdf.png
    hosts:
      - host: &host pdf.hermleigh.cc
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: external-wildcard-certificate
