# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/main/bitnami/mysql/values.schema.json
auth:
  existingSecret: mysql-secret
metrics:
  enabled: true
primary:
  persistence:
    existingClaim: mysql
  podSecurityContext:
    enabled: true
    fsGroup: 997
  containerSecurityContext:
    enabled: true
    runAsUser: 997
    runAsNonRoot: true
  service:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.16.1.32
      external-dns.alpha.kubernetes.io/hostname: mysql.hermleigh.home
    type: LoadBalancer
