worker:
  annotations:
    configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
  config:
    core:
      sources:
        - custom
        - pci
        - usb
    sources:
      usb:
        deviceClassWhitelist:
          - "02"
          - "03"
          - "0e"
          - "ef"
          - "fe"
          - "ff"
        deviceLabelFields:
          - class
          - vendor
          - device
  prometheus:
    enable: true
