---
- name: Reset K8S cluster
  hosts: kube_control_plane
  any_errors_fatal: true
  gather_facts: true
  become: true
  tags:
    - cluster
  tasks:
    - name: Run resets from relevant roles
      include_role:
        name: "{{ item }}"
        tasks_from: reset
      with_items:
        # - apps
        - kubernetes/control_plane
        - containers/runtime

    - name: Reset | include file with reset tasks specific to the network_plugin if exists
      include_role:
        name: "containers/network/{{ kube_network_plugin }}"
        tasks_from: reset
      when:
        - kube_network_plugin in ['flannel', 'cilium', 'kube-router', 'calico']
      tags:
        - network

- name: Tear down terraform stacks
  hosts: localhost
  tags:
    - terraform
  tasks:
    - name: Tear down terraform stack
      community.general.terraform:
        project_path: "{{ (infra_dir, 'terraform', item) | path_join }}"
        state: absent
      when: item is directory
      with_fileglob:
        - "{{ infra_dir }}/terraform/*"
