---
# Some Debian based distros ship without Python installed
- name: Check if bootstrap is needed
  raw: which python3
  register: need_bootstrap
  failed_when: false
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  tags:
    - facts

- name: Locale
  block:
    - name: Locale | Set timezone
      community.general.timezone:
        name: "{{ timezone | default('Etc/UTC') }}"

- name: Networking
  block:
    - name: Networking | Set hostname to inventory hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Networking | Update /etc/hosts to include inventory hostname
      blockinfile:
        path: /etc/hosts
        block: |
          127.0.1.1   {{ inventory_hostname }}

- name: Mount configuration
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: "{{ item.state }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
  loop: "{{ mounts | default({}) }}"
  when: item.use | default(true)

- name: Create local ansible user
  include_role:
    name: user
    tasks_from: system-user.yml

- name: Perms on /usr/local/bin
  file:
    dest: /usr/local/bin
    state: directory
    owner: root
    group: sys
    mode: "0775"

- name: Disable sshd password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

- name: Ensure bash_completion.d folder exists
  file:
    name: /etc/bash_completion.d/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Set console for High DPI monitor
  blockinfile:
    path: /etc/default/console-setup
    state: present
    block: |
      CODESET="Uni3"
      FONTFACE="Terminus"
      FONTSIZE="32x16"

- name: Run package install
  include_tasks: packages.yml

# - name: Enable vlan kernel modules now
#   community.general.modprobe:
#     name: 80
#     state: present
#   with_items:
#     - 8021q

# - name: Enable kernel modules on boot
#   copy:
#     mode: '0644'
#     content: "{{ item }}"
#     dest: "/etc/modules-load.d/{{ item }}.conf"
#   with_items:
#     - 8021q

- name: Manage IP addresses on parche
  when: inventory_hostname == 'parche'
  block:
    - name: parche | Manage interface bond0 config file
      blockinfile:
        path: /etc/network/interfaces.d/bond0
        create: true
        content: |-
          auto bond0
          iface bond0 inet manual
            bond-slaves enp11s0 enp12s0
            bond-mode 802.3ad
            bond-miimon 100
            bond-downdelay 200
            bond-updelay 200
            bond-min-links 1
      register: ifcfg_bond0

    - name: parche | Manage interface br0 config file
      blockinfile:
        path: /etc/network/interfaces.d/br0
        create: true
        content: |-
          auto br0
          iface br0 inet static
            address 172.16.1.10
            network 172.16.1.0
            netmask 255.255.255.0
            broadcast 172.16.1.255
            gateway 172.16.1.1
            dns-nameservers 172.16.1.1
            dns-search hermleigh.home
            bridge_ports bond0
            bridge_stp on
            bridge_waitport 0
          iface br0 inet static
            address 172.16.1.11
            network 172.16.1.0
            netmask 255.255.255.0
            broadcast 172.16.1.255

      register: ifcfg_br0

    - name: parche | Manage interface br1 config file
      blockinfile:
        path: /etc/network/interfaces.d/br1
        create: true
        content: |-
          auto br1
          iface br1 inet static
            address 172.17.1.10
            netmask 255.255.255.0
            gateway 172.17.1.1
            broadcast 172.17.1.255
            dns-domain hermleigh.home
            dns-nameservers 172.17.1.1
            bridge_ports enp0s31f6
            bridge_stp on
            bridge_waitport 0
          iface br1 inet static
            address 172.17.1.11
            network 172.17.1.0
            netmask 255.255.255.0
            broadcast 172.17.1.255

      register: ifcfg_br1

    - name: restart networking # noqa no-handler
      service:
        name: networking
        state: restarted
      when: ifcfg_bond0 is changed or ifcfg_br0 is changed or ifcfg_br1 is changed

- name: Load Root CA into system ca trust store
  copy:
    dest: "/usr/local/share/ca-certificates/{{ domain_name }}-root.crt"
    content: "{{ root_ca.crt | b64decode }}"
  notify:
    - "update ca truststore"
